KnightmareLeon/residential-rentals-utilities-tracker

- main.py
Added code to dynamically load custom fonts from assets into the GUI
> feat(font): Add custom font

- src/utils/constants.py
- src/views/components/BaseTableWidget.py
- src/views/components/UtilityTable.py
- src/views/mainWindow.py
Added Utility Table; Refactored Table classes so that there is a parent TableWidget class that Units Table, Utilities Table, and Bills Table will inherit from; Added foundation for connecting searchbar and table updates.
> feat(views): Added UtilityTable.py

- src/views/MainWindow.py
- src/views/components/BaseTableWidget.py
- src/views/components/BillsTable.py
- src/views/components/UnitsTable.py
- src/views/components/UtilitiesTable.py
Added BillsTable, Added separate page searching so that the searchbar text will depend on what page you are on when you searched it
> feat(views): Added BillsTable and Separate Page Searching

- src/models/DatabaseDriver.py
- Delete method can delete by batch.
- Update documentation on the read method.
> feat(batchDelete): Delete method can delete by batch

- BACKEND_REQUESTS.md
- src/utils/sampleDataGenerator.py
- src/views/MainWindow.py
- src/views/components/BaseTableWidget.py
- src/views/components/BillsTable.py
- src/views/components/UnitsTable.py
- src/views/components/UtilitiesTable.py
- src/views/pages/BasePageWidget.py
- src/views/pages/BillsPage.py
- src/views/pages/UnitsPage.py
- src/views/pages/UtilitiesPage.py
Added a Page widget to encompass the Table widgets and the Button controls, Added button controls that include Add button and Pagination controls, Fixed some visual bugs
> feat(views): Added Page widgets and Button controls

- src/views/components/BaseTableWidget.py
Fixed table header color into white
> fix(table): Fixed table header color

- src/controllers/billsController.py
- src/controllers/unitsController.py
- src/controllers/utilitiesController.py
- src/views/MainWindow.py
- src/views/components/BaseTableWidget.py
- src/views/components/BillsTable.py
- src/views/components/UnitsTable.py
- src/views/components/UtilitiesTable.py
- src/views/pages/BasePageWidget.py
- src/views/pages/BillsPage.py
- src/views/pages/UnitsPage.py
- src/views/pages/UtilitiesPage.py
Added Controllers scaffolding and refactored views.
> refactor(controllers): Refactor Views to add Controllers

- src/views/components/UtilityDashboard.py
- src/views/widgets/CheckableComboBox.py
Added chart filtering for UtilityDashboard. It uses a checkable combobox to track which utilities to display in the chart. Added chart hover feature that displays the exact amount for each point of the chart when hovering over the ponit.
> feat(dashboard): Added chart filtering and Hover for details

- src/views/components/UtilityDashboard.py
- src/views/widgets/CheckableComboBox.py
Fixed custom combobox visual and hover feature bugs
> fix(dashboard): Fix filter combobox bugs

- BACKEND_REQUESTS.md
- src/controllers/billsController.py
- src/controllers/dashboardController.py
- src/controllers/unitsController.py
- src/controllers/utilitiesController.py
- src/views/components/BillsDashboard.py
- src/views/components/BillsTable.py
- src/views/components/UnitsTable.py
- src/views/components/UtilitiesTable.py
- src/views/components/UtilityDashboard.py
- src/views/pages/BillsPage.py
- src/views/pages/UnitsPage.py
- src/views/pages/UtilitiesPage.py
- src/views/widgets/BillEntry.py
Added dashboard controller foundation (not implementation). Updated docs for backend requests.
> feat(controllers): Added dashbaordController

- src/views/components/BillsDashboard.py
Fixed syntax error in billsDashboard
> fix(views): Fixed billsDashboard bug

- src/controllers/dashboardController.py
- src/views/components/UtilityDashboard.py
Added pagination feature to UtilityDashboard and updated dashboardController.
> feat(views): Added UtilityDashboard pagination

- src/models/BillDatabaseTable.py
- urgentBills method in BillsDatabaseTable class gets up to 15 (default) bills that are unpaid and prioritized based on their closeness to their due date
- Refactor getting the rangeClause for methods that have a range argument, uses a private method to get it now
> feat(urgentBills): Get urgent bills

- src/views/components/UtilityDashboard copy.py
- src/views/widgets/BaseViewWidget.py
- src/views/widgets/UnitViewWidget.py
- src/views/widgets/UtilityChartWidget.py
Refactored UtilityDashboard to allow reusable ChartWidgets
> refactor(views): Refactore UtilityDashboard

- src/views/widgets/BillEntry.py
- src/views/widgets/UtilityChartWidget.py
Fixed utilityDashboard hover date. It used to display the x axis value it fits in instead of the actual date. Removed billsDashboard text wrapping and replaced with fixed width columns
> fix(views): Fixed minor visual bugs

- src/models/BillDatabaseTable.py
- Complementary methods to get the maximum offset for a unit's bills, a utility's bills, and for all unit's bills.
> feat(bills): Add method to get the max offset for bills

- src/controllers/unitsController.py
- src/utils/sampleDataGenerator.py
- src/views/components/BillView.py
- src/views/components/BillsDashboard.py
- src/views/pages/HomePage.py
- src/views/widgets/BaseViewWidget.py
Refactored UnitView and BaseViewWidget to fix visual bugs. Added "View All" functionality for BillDashboard button
> refactor(view): Refactored code for UnitView and BillDashboard

- main.py
- src/controllers/billsController.py
- src/utils/constants.py
- src/views/components/BillView.py
- src/views/components/BillsDashboard.py
- src/views/components/BillsTable.py
- src/views/components/UnitsTable.py
- src/views/widgets/BaseViewWidget.py
- src/views/widgets/UtilityChartWidget.py
Added BillView to UtilityChartWidget, BillDashboard, and BillTable
> feat(views): Added BillView and implemented it throughout the GUI

- src/controllers/billsController.py
- src/controllers/utilitiesController.py
- src/utils/constants.py
- src/utils/sampleDataGenerator.py
- src/views/components/BillsDashboard.py
- src/views/components/UtilitiesTable.py
- src/views/components/UtilityDashboard.py
- src/views/components/UtilityView.py
- src/views/widgets/UtilityChartWidget.py
Added UtilityView, Refactored UtilityChartWidget to handle single utilities
> feat(views): Added UtilityView

- main.py
- src/views/dialogs/AddUnitForm.py
- src/views/dialogs/AddUtilityForm.py
- src/views/widgets/BaseCreateWidget.py
Fixed visual bugs in AddUnitDialog, AddUtilityDialog. Added setStyle Fusion across GUI.
> fix(views): Fixed AddDialog visual bugs

- src/controllers/dashboardController.py
- src/controllers/unitsController.py
- src/controllers/utilitiesController.py
- src/utils/constants.py
- src/views/components/BillsDashboard.py
- src/views/components/BillsTable.py
- src/views/components/UnitsTable.py
- src/views/components/UtilitiesTable.py
- src/views/dialogs/AddBillForm.py
- src/views/dialogs/BillView.py
- src/views/dialogs/EditBillForm.py
- src/views/dialogs/EditUnitForm.py
- src/views/dialogs/EditUtilityForm.py
- src/views/dialogs/UnitView.py
- src/views/dialogs/UtilityView.py
- src/views/widgets/BaseEditWidget.py
- src/views/widgets/BaseViewWidget.py
Refactored all View Forms to handle a fix in the relationship between Units and Utilities. Updated controller outputs for the views.
> refactor(views): Refactored all View forms and Updated Controllers

- src/controllers/billsController.py
- src/controllers/unitsController.py
- src/controllers/utilitiesController.py
- src/utils/constants.py
- src/utils/sampleDataGenerator.py
- src/views/dialogs/AddBillForm.py
- src/views/dialogs/AddUtilityForm.py
- src/views/dialogs/EditBillForm.py
- src/views/pages/BillsPage.py
- src/views/pages/UtilitiesPage.py
- src/views/widgets/BaseCreateWidget.py
Fixed all fetch utilities by unit requests and fixed data handling logic in Create widgets. Replaced all instances of 'Wifi' with 'Internet'
> fix(views): Fixed fetch utilities controllers in Create widgets

- src/controllers/dashboardController.py
- src/controllers/unitsController.py
- src/controllers/utilitiesController.py
- src/views/components/UtilitiesTable.py
- src/views/dialogs/EditUtilityForm.py
- src/views/pages/UnitsPage.py
- src/views/widgets/BaseCreateWidget.py
- src/views/widgets/BaseEditWidget.py
Refactored EditUtilityForm to handle shared units editing, disabling pre-existing utility types, and preselecting units already shared by the utility. Updated controller scaffolding.
> Refactor(views): Refactored EditUtilityForm

- src/views/components/BillsTable.py
- src/views/components/UnitsTable.py
- src/views/components/UtilitiesTable.py
- src/views/dialogs/AddUtilityForm.py
- src/views/dialogs/EditBillForm.py
- src/views/dialogs/EditUnitForm.py
- src/views/dialogs/EditUtilityForm.py
- src/views/pages/BillsPage.py
- src/views/pages/UnitsPage.py
- src/views/pages/UtilitiesPage.py
Added confirmation dialogs to CreateWidgets, EditWidgets, and delete buttons.
> feat(views): Added confirmation and notification dialogs

- src/controllers/billsController.py
- src/controllers/unitsController.py
- src/controllers/utilitiesController.py
- src/views/MainWindow.py
- src/views/components/BillsTable.py
- src/views/components/UnitsTable.py
- src/views/components/UtilitiesTable.py
- src/views/widgets/BaseTableWidget.py
Fixed update table visual bugs. Connected Tables to Controller functions.
> fix(views): Fixed visual bugs
